services:
  mongodb:
    image: mongo:latest
    container_name: pokedex-db
    restart: always
    ports:
      - "27018:27017"
    volumes:
      - ./data/db:/data/db
      - ./data/configdb:/data/configdb
      - ./data:/data
      - ./infra/mongo-init:/docker-entrypoint-initdb.d
    networks:
      - pokedex-net

  client:
    build: .
    container_name: langgraph-client
    stdin_open: true 
    tty: true
    depends_on:
      - mongodb
    env_file: .env
    volumes:
      - .:/app
    environment:  
      - MONGO_URL=mongodb://mongodb:27017/
    networks:
      - pokedex-net

networks:
  pokedex-net:
    driver: bridge